### ISSUE TITLE
Possible Performance Improvements for cc3d

### ISSUE THREAD

**Issue by william-silversmith** [siahuat0727/tirf#1]
Hi! I was just browsing packages that are using cc3d and I'm glad you decided to use it! I noticed that you seemed to be having performance issues with extracting certain properties like bounding boxes and voxel counts from images in https://github.com/siahuat0727/tirf/blob/12b75625e530744abb36a61ef96f4ff741203b8b/utils/play.py. 

cc3d also has other operators that are designed to do some of what you're looking for.

```
cc, N = cc3d.connected_components(..., return_N=True) # get number of components (which are numbered sequentially from 1)
stats = cc3d.statistics(cc) # bounding boxes, voxel counts

# extracting binary images for each label at high efficiency
for label, image in cc3d.each(labels_out, binary=False, in_place=True):
  process(image) # stand in for whatever you'd like to do
```

There are also operators for removing dust `cc3d.dust` and `cc3d.largest_k`. 

If this isn't necessary for your project, please feel free to ignore this, but I hope this advice is helpful! Good luck on your project!

**Comment by siahuat0727** [comment]
Hi @william-silversmith
That's exactly what I am looking for!
Thank you so much for your super helpful suggestion and I really appreciate your project. :)


~~And ... I'm so sorry to let you go through this unready code... :sweat_smile:~~

**Comment by william-silversmith** [comment]
I'm so glad it's helpful! Good luck on your project. Don't worry about the state of your code. I'm glad you shared it so I could see and help. :) <3
